# Generated by Django 2.1.3 on 2022-02-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discountID', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='finalbill',
            name='discountID',
        ),
    ]
