# Generated by Django 2.1.3 on 2022-02-14 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_billing', '0002_auto_20220213_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(default='AP1', max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='FinalBill',
        ),
        migrations.AddField(
            model_name='discount',
            name='dicount_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discount',
            name='product_id',
            field=models.ForeignKey(default='AP1', on_delete=django.db.models.deletion.CASCADE, to='market_billing.Product'),
            preserve_default=False,
        ),
    ]
